
export const LOGINSTATE_TRUE = "LOGINSTATE_TRUE"; //登录
export const LOGINSTATE_FALSE = "LOGINSTATE_FALSE";//未登录

export const ERRORSTATE_TRUE = 'ERRORSTATE_TRUE';//显示错误提示
export const ERRORSTATE_FALSE = 'ERRORSTATE_FALSE';//隐藏错误提示

export const COUNTDOWNSTATE_TRUE = 'COUNTDOWNSTATE_TRUE';//倒计时开始
export const COUNTDOWNSTATE_FALSE= 'COUNTDOWNSTATE_FALSE';//倒计时结束
